In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [25]:
path_test = "C:/Users/Ihab/Desktop/Preprocessing/test.csv"
path_train = "C:/Users/Ihab/Desktop/Preprocessing/train.csv"
train = pd.read_csv(path_train)
test = pd.read_csv(path_test)

In [26]:
def clean(df):
    df.drop(['Name','Ticket','Fare','Cabin'],axis='columns',inplace=True)
    for i in ["Age"]:
        df[i].fillna(df[i].median(),inplace=True)
    return df

In [27]:
clean(train)

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0              1         0       3    male  22.0      1      0        S
1              2         1       1  female  38.0      1      0        C
2              3         1       3  female  26.0      0      0        S
3              4         1       1  female  35.0      1      0        S
4              5         0       3    male  35.0      0      0        S
..           ...       ...     ...     ...   ...    ...    ...      ...
886          887         0       2    male  27.0      0      0        S
887          888         1       1  female  19.0      0      0        S
888          889         0       3  female  28.0      1      2        S
889          890         1       1    male  26.0      0      0        C
890          891         0       3    male  32.0      0      0        Q

[891 rows x 8 columns]

In [10]:
clean(test)

     PassengerId  Pclass     Sex   Age  SibSp  Parch Embarked
0            892       3    male  34.5      0      0        Q
1            893       3  female  47.0      1      0        S
2            894       2    male  62.0      0      0        Q
3            895       3    male  27.0      0      0        S
4            896       3  female  22.0      1      1        S
..           ...     ...     ...   ...    ...    ...      ...
413         1305       3    male  27.0      0      0        S
414         1306       1  female  39.0      0      0        C
415         1307       3    male  38.5      0      0        S
416         1308       3    male  27.0      0      0        S
417         1309       3    male  27.0      1      1        C

[418 rows x 7 columns]

In [28]:
mask = train['Embarked'].isnull()
train = train[~mask]

In [29]:
train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
dtype: int64

In [30]:
clean(test)
mask = test['Embarked'].isnull()
test = test[~mask]

In [31]:
test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
dtype: int64

In [35]:
train = pd.get_dummies(data=train,columns=['Sex'])

In [36]:
test = pd.get_dummies(data=test,columns=['Sex'])

In [37]:
train = pd.get_dummies(data=train,columns=['Embarked'])

In [38]:
test = pd.get_dummies(data=test,columns=['Embarked'])

In [39]:
train

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,False,True,False,False,True
1,2,1,1,38.0,1,0,True,False,True,False,False
2,3,1,3,26.0,0,0,True,False,False,False,True
3,4,1,1,35.0,1,0,True,False,False,False,True
4,5,0,3,35.0,0,0,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,False,True,False,False,True
887,888,1,1,19.0,0,0,True,False,False,False,True
888,889,0,3,28.0,1,2,True,False,False,False,True
889,890,1,1,26.0,0,0,False,True,True,False,False
890,891,0,3,32.0,0,0,False,True,False,True,False

In [40]:
test

,PassengerId,Pclass,Age,SibSp,Parch,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,3,34.5,0,0,False,True,False,True,False
1,893,3,47.0,1,0,True,False,False,False,True
2,894,2,62.0,0,0,False,True,False,True,False
3,895,3,27.0,0,0,False,True,False,False,True
4,896,3,22.0,1,1,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,27.0,0,0,False,True,False,False,True
414,1306,1,39.0,0,0,True,False,True,False,False
415,1307,3,38.5,0,0,False,True,False,False,True
416,1308,3,27.0,0,0,False,True,False,False,True
417,1309,3,27.0,1,1,False,True,True,False,False

In [48]:
x = train.drop(['Survived'],axis = 1)
y = train.Survived
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=.8)
accuracies = []

In [49]:
def all(model):
    model.fit(x_train,y_train)
    pre = model.predict(x_train)
    accuracy = accuracy_score(y_train,pre)
    print("Accuracy is " ,accuracy)
    accuracies.append(accuracy)

In [50]:
model1=SVC()
model2=GaussianNB()
model3=DecisionTreeClassifier()
model4 = GradientBoostingClassifier()
model5 = KNeighborsClassifier()
model6 = RandomForestClassifier()
model7 = LogisticRegression(max_iter=200)

In [51]:
all(model1)
all(model2)
all(model3)
all(model4)
all(model5)
all(model6)
all(model7)

Accuracy is  0.6230661040787623
Accuracy is  0.7749648382559775
Accuracy is  1.0
Accuracy is  0.8945147679324894
Accuracy is  0.7243319268635724
Accuracy is  1.0
Accuracy is  0.7932489451476793

c:\users\ihab\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [52]:
modelv2 = RandomForestClassifier()
modelv2.fit(x_train,y_train)

RandomForestClassifier()

In [53]:
rfc = modelv2.predict(test)

In [54]:
final = test.PassengerId
dernier_df = pd.DataFrame({'PassengerId':final,'Survived':rfc})
dernier_df.to_csv('submissionv2.csv',index=False)